# Generated by Django 3.1.2 on 2021-05-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_list_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='list_header_image',
            new_name='profile_pic',
        ),
    ]
