# Generated by Django 3.1.2 on 2021-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210821_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
