# Generated by Django 3.1.2 on 2021-01-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20201231_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-article_date',)},
        ),
    ]
