# Generated by Django 3.1.2 on 2021-01-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20210103_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detail_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
