# Generated by Django 3.1.2 on 2021-05-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20210513_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
